FROM jenkins/jenkins:jdk21
# cat /etc/*/release

WORKDIR /tmp
RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
RUN unzip awscliv2.zip
USER root
RUN ./aws/install

RUN apt update
RUN apt install python3-full -y
RUN apt install pip -y
RUN pip install checkov --ignore-installed --break-system-packages
RUN jenkins-plugin-cli --plugins "blueocean:1.25.6 docker-workflow:1.29"

# apt install wget
# wget https://www.python.org/ftp/python/3.11.3/Python-3.11.3.tgz
# tar -xf Python-3.11.3.tgz
# CD Python-3.11.3 && ./configure --enable-optimizations
# make -j 12
# make