pipeline {
    
    agent {
        docker {
            image 'jenkins-checkov:latest'
        }
    }

    stages {
        
        stage ('checkov disable skip') {
            steps {
                script {
                    sh "echo 'Iniciando escaneo de Checkov'"
                }
            }
        }

        stage ('Security Scan (Checkov)') {
            steps {
                script {
                    echo "Ejecutando Checkov para escanear el código..."
                    
 
                    sh "checkov -d ./dockerCheckov/ -o junit --output-file checkov_report.xml"
                }
            }
        }

        stage ('Deploy') {
            steps {
                script {
                    sh "echo 'Iniciando despliegue...'"
                }
            }
        }
    }
    
    post {

        always {
            script {
                echo "Publicando reporte de Checkov en la interfaz de Jenkins..."

                junit 'dockerCheckov/checkov_report.xml'
            }
        }
    }
}